.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH BACKUPNINJA.CONF 5 "November 19, 2005" "riseup" "backupninja package"
.SH NAME 
BACKUPNINJA.CONF \- Configuration file(s) for \fBbackupninja (1)\fP.

.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.br
.SH SYNOPSIS
.B "/etc/backupninja.conf "
.br
.SH DESCRIPTION
.B backupninja.conf
is the general configuration file. In this file you can set the log level and change the default directory locations.  You can force a different general configuration file with "backupninja \-f /path/to/conf".

.SH OPTIONS

.TP
.B loglevel
How verbose to make the logs. 
.br
5 = Debugging messages
.br
4 = Informational messages
.br
3 = Warnings
.br
2 = Errors
.br
1 = Fatal errors 

.TP
.B reportemail
Send a summary of the backup status to this email address

.TP
.B reportsuccess
If set to 'yes', a report email will be generated even if all modules reported success.

.TP
.B reportwarning
If set to 'yes', a report email will be generated even if there was no error.

.TP
.B logfile
The path of the logfile.

.TP
.B configdirectory
The directory where all the backup action configuration files live.

.TP 
.B scriptdirectory 
Where backupninja handler scripts are found

.TP
.B usecolors
If set to 'yes', use colors in the log file and debug output.

.TP
.B when
When to process each configuration file. The value used here will
be applied for each configuration file. It is possibile to override
this "when" in each each configuration file, see also section 
"Scheduling" in backup.d(5).

For example:

  when = sundays at 02:00
  when = 30th at 22
  when = 30 at 22:00
  when = everyday at 01            <-- the default
  when = Tuesday at 05:00

These values for 'when' are equivalent:

  when = tuesday at 05:30
  when = TUESDAYS at 05

These values for 'when' are invalid:
  
  when = tuesday at 2am
  when = tuesday at 2
  when = tues at 02

.TP
.B vservers
If you are using Linux-Vservers (http://linux-vserver.org), there are some
special capabilities that different handlers have to make vserver backups easier.
See the example configuration files for each handler to configure the vserver specific
variables.

.SH DEFAULTS

loglevel = 4
.br
reportemail = root
.br
reportsuccess = yes
.br
reportwarning = yes
.br
logfile = /var/log/backupninja.log
.br
configdirectory = /etc/backup.d
.br
scriptdirectory = /usr/share/backupninja
.br
usecolors = yes 
.br
when = everyday at 01:00
.br
vservers = no

.SH SEE ALSO
.BR backupninja (1), 
.BR ninjahelper (1), 
.BR backup.d (5), 
.br
.SH AUTHOR
BACKUPNINJA was written by the riseup.net collective.
